#!/usr/bin/env python3
"""Explicit, budgeted recovery inventory; standard library, no recursive discovery.

plan and verify never write. Only synthetic-drill writes, exclusively into a new
child of the system temporary directory, using generated bytes. Runtime manifests
contain operator-supplied file locators and must remain outside public Git.
"""
from __future__ import annotations

import argparse
from contextlib import contextmanager
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import sys
import tempfile
from typing import Mapping


SCHEMA = "vkm-unique-inventory/1"
TOOL = "vkm-unique-recovery/1"
CHUNK = 1 << 20
MAX_MANIFEST_BYTES = 1 << 20
MAX_ITEMS = 10000
ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,99}$")
SHA = re.compile(r"^[0-9a-f]{64}$")
ENV = re.compile(r"^[A-Z][A-Z0-9_]{0,99}$")


class InventoryError(ValueError):
    """A fixed diagnostic code, never an exception containing a private locator."""


def _bytes(value) -> bytes:
    return json.dumps(value, sort_keys=True, ensure_ascii=True, separators=(",", ":")).encode("ascii")


def _digest(value) -> str:
    return hashlib.sha256(_bytes(value)).hexdigest()


def _keys(value, required, optional=()):
    if not isinstance(value, dict) or not set(required) <= value.keys() or value.keys() - set(required) - set(optional):
        raise InventoryError("INVALID_MANIFEST")


def _identifier(value):
    if not isinstance(value, str) or not ID.fullmatch(value):
        raise InventoryError("INVALID_IDENTIFIER")


def _relative(value):
    if not isinstance(value, str) or not value or "\\" in value or ":" in value or "\x00" in value:
        raise InventoryError("UNSAFE_LOCATOR")
    path = PurePosixPath(value)
    if path.is_absolute() or any(p in {"", ".", ".."} for p in value.split("/")):
        raise InventoryError("UNSAFE_LOCATOR")
    # Windows alternate streams, device names, trailing dots/spaces and wildcards
    # are rejected on every host, so one manifest has portable file identity.
    for part in path.parts:
        stem = part.split(".", 1)[0].upper()
        if (part.endswith((".", " ")) or any(c in part for c in '<>"|?*') or
                any(ord(c) < 32 for c in part) or stem in {"CON", "PRN", "AUX", "NUL"} or
                re.fullmatch(r"(?:COM|LPT)[1-9]", stem)):
            raise InventoryError("UNSAFE_LOCATOR")


def validate_manifest(manifest: dict) -> dict:
    """Validate declarations only. REPRODUCIBLE is a declaration, not a restore PASS."""
    _keys(manifest, {"schema", "roots", "items"})
    if manifest["schema"] != SCHEMA or not isinstance(manifest["roots"], list) or not isinstance(manifest["items"], list):
        raise InventoryError("INVALID_MANIFEST")
    if not 1 <= len(manifest["roots"]) <= 100 or not 1 <= len(manifest["items"]) <= MAX_ITEMS:
        raise InventoryError("MANIFEST_LIMIT")
    roots = {}
    for root in manifest["roots"]:
        _keys(root, {"root_id", "location_env", "failure_domain", "role"})
        _identifier(root["root_id"])
        _identifier(root["failure_domain"])
        if not isinstance(root["location_env"], str) or not ENV.fullmatch(root["location_env"]):
            raise InventoryError("INVALID_ENV_LOCATOR")
        key = root["root_id"].casefold()
        if key in roots or root["role"] not in {"ORIGINAL", "COPY"}:
            raise InventoryError("DUPLICATE_OR_INVALID_ROOT")
        roots[key] = root
    items, locators = {}, set()

    def locator(ref, role):
        _keys(ref, {"root_id", "path"})
        _identifier(ref["root_id"])
        _relative(ref["path"])
        root = roots.get(ref["root_id"].casefold())
        if root is None or root["root_id"] != ref["root_id"] or root["role"] != role:
            raise InventoryError("INVALID_ROOT_REFERENCE")
        return ref["root_id"].casefold(), ref["path"].casefold()

    for item in manifest["items"]:
        _keys(item, {"logical_id", "classification", "source", "mutable", "copies"},
              {"expected_sha256", "reproduction"})
        _identifier(item["logical_id"])
        key = item["logical_id"].casefold()
        if key in items:
            raise InventoryError("DUPLICATE_LOGICAL_ID")
        if item["classification"] not in {"CANONICAL", "REPRODUCIBLE"} or type(item["mutable"]) is not bool:
            raise InventoryError("INVALID_CLASSIFICATION")
        source = locator(item["source"], "ORIGINAL")
        if source in locators:
            raise InventoryError("DUPLICATE_SOURCE_LOCATOR")
        locators.add(source)
        if not isinstance(item["copies"], list) or len(item["copies"]) > 16:
            raise InventoryError("MANIFEST_LIMIT")
        copies = [locator(ref, "COPY") for ref in item["copies"]]
        if len(set(copies)) != len(copies):
            raise InventoryError("DUPLICATE_COPY_LOCATOR")
        if "expected_sha256" in item and (not isinstance(item["expected_sha256"], str) or not SHA.fullmatch(item["expected_sha256"])):
            raise InventoryError("INVALID_EXPECTED_HASH")
        if item["classification"] == "REPRODUCIBLE":
            recipe = item.get("reproduction")
            _keys(recipe, {"recipe_sha256", "input_ids"})
            if not isinstance(recipe["recipe_sha256"], str) or not SHA.fullmatch(recipe["recipe_sha256"]):
                raise InventoryError("INVALID_REPRODUCTION")
            if not isinstance(recipe["input_ids"], list) or len(set(recipe["input_ids"])) != len(recipe["input_ids"]):
                raise InventoryError("INVALID_REPRODUCTION")
            for ref in recipe["input_ids"]:
                _identifier(ref)
        elif "reproduction" in item:
            raise InventoryError("INVALID_REPRODUCTION")
        items[key] = item
    visiting, complete = set(), set()

    def visit(key):
        if key in visiting:
            raise InventoryError("REPRODUCTION_CYCLE")
        if key in complete:
            return
        visiting.add(key)
        for ref in items[key].get("reproduction", {}).get("input_ids", []):
            target = items.get(ref.casefold())
            if target is None or target["logical_id"] != ref:
                raise InventoryError("UNKNOWN_REPRODUCTION_INPUT")
            visit(ref.casefold())
        visiting.remove(key)
        complete.add(key)

    for key in items:
        visit(key)
    return manifest


def _absolute(path) -> Path:
    # Do not resolve(): that would silently follow a symlink before inspecting it.
    return Path(os.path.abspath(os.fspath(path)))


def _indirect(info) -> bool:
    return stat.S_ISLNK(info.st_mode) or bool(getattr(info, "st_file_attributes", 0) & 0x400)


def _metadata(path: Path) -> os.stat_result:
    path = _absolute(path)
    for component in (*reversed(path.parents), path):
        info = component.lstat()
        if _indirect(info):
            raise InventoryError("SYMLINK_OR_REPARSE_POINT")
        if component != path and not stat.S_ISDIR(info.st_mode):
            raise InventoryError("NON_DIRECTORY_ANCESTOR")
    if not stat.S_ISREG(info.st_mode):
        raise InventoryError("NOT_REGULAR_FILE")
    if os.name == "nt":
        # Python/Windows path stat and descriptor stat can expose different
        # meanings of ctime (creation versus change time). Use descriptor
        # metadata consistently; opening this handle does not read any bytes.
        with _open_regular(path) as file:
            return os.fstat(file.fileno())
    return info


def _stamp(info) -> dict:
    return {"device": info.st_dev, "inode": info.st_ino, "size": info.st_size,
            "mtime_ns": info.st_mtime_ns, "ctime_ns": info.st_ctime_ns, "mode": info.st_mode}


def _failure(exc) -> str:
    if isinstance(exc, InventoryError):
        return str(exc)
    if isinstance(exc, FileNotFoundError):
        return "MISSING"
    if isinstance(exc, PermissionError):
        return "ACCESS_DENIED"
    return "IO_ERROR"


def _resolve(manifest, environ):
    roots = {}
    bindings = {}
    for root in manifest["roots"]:
        raw = environ.get(root["location_env"])
        if not raw or not Path(raw).is_absolute():
            roots[root["root_id"]] = None
            bindings[root["root_id"]] = "ROOT_UNAVAILABLE"
        else:
            roots[root["root_id"]] = _absolute(raw)
            bindings[root["root_id"]] = _digest(str(roots[root["root_id"]]))
    return roots, bindings


def _inspect(ref, roots):
    root = roots[ref["root_id"]]
    result = {"root_id": ref["root_id"]}
    if root is None:
        return {**result, "status": "ROOT_UNAVAILABLE"}
    try:
        info = _metadata(root / ref["path"])
        return {**result, "status": "REGULAR", "size_bytes": info.st_size, "identity": _stamp(info)}
    except (OSError, InventoryError) as exc:
        return {**result, "status": _failure(exc)}


def plan(manifest: dict, *, byte_budget: int | None, environ: Mapping[str, str] | None = None) -> dict:
    """Metadata-only inventory. No directory walk, file-content hash or writes."""
    validate_manifest(manifest)
    roots, bindings = _resolve(manifest, os.environ if environ is None else environ)
    rows, maximum = [], 0
    for item in sorted(manifest["items"], key=lambda i: i["logical_id"]):
        source = _inspect(item["source"], roots)
        copies = [_inspect(ref, roots) for ref in item["copies"]]
        if not item["mutable"]:
            # Reserve one extra byte per file to detect growth without ever
            # reading beyond the caller's budget. EOF itself consumes no bytes.
            # Two full passes: metadata timestamps can be coarse/cached and are
            # not a sufficient guard against an in-place same-size replacement.
            maximum += 2 * sum(value["size_bytes"] + 1 for value in (source, *copies) if value["status"] == "REGULAR")
        rows.append({"logical_id": item["logical_id"], "declared_classification": item["classification"],
                     "mutable": item["mutable"], "source": source, "copies": copies,
                     "backup_status": "NOT_VERIFIED", "recovery_classification": "REPRODUCIBLE"
                     if item["classification"] == "REPRODUCIBLE" else "UNBACKED_UNIQUE"})
    budget_ok = type(byte_budget) is int and byte_budget > 0
    blocker = "BYTE_BUDGET_REQUIRED" if not budget_ok else "BYTE_BUDGET_EXCEEDED" if maximum > byte_budget else None
    result = {"schema": "vkm-unique-recovery-plan/1", "tool": TOOL, "manifest_sha256": _digest(manifest),
              "root_bindings": bindings, "byte_budget": byte_budget if budget_ok else None,
              "max_bytes_to_read": maximum, "bytes_read": 0, "recursive_discovery": False,
              "status": "BLOCKED" if blocker else "READY", "blocker": blocker, "items": rows}
    result["plan_sha256"] = _digest(result)
    return result


@dataclass
class ByteBudget:
    maximum: int
    used: int = 0

    def read(self, file, length: int) -> bytes:
        if length > self.maximum - self.used:
            raise InventoryError("BYTE_BUDGET_EXCEEDED")
        value = file.read(length)
        self.used += len(value)
        return value


@contextmanager
def _open_regular(path: Path):
    """Pin ancestors and refuse link traversal, including Windows junctions.

    POSIX uses openat/O_NOFOLLOW at every component. Windows retains non-delete-
    shared ancestor handles; the file handle denies write/delete while reading.
    These are advisory process-level guards, not a filesystem snapshot.
    """
    path = _absolute(path)
    handles = []
    file = None
    if os.name == "nt":
        import ctypes
        from ctypes import wintypes
        import msvcrt
        kernel = ctypes.WinDLL("kernel32", use_last_error=True)
        create = kernel.CreateFileW
        create.argtypes = [wintypes.LPCWSTR, wintypes.DWORD, wintypes.DWORD, ctypes.c_void_p,
                           wintypes.DWORD, wintypes.DWORD, wintypes.HANDLE]
        create.restype = wintypes.HANDLE
        close = kernel.CloseHandle
        close.argtypes = [wintypes.HANDLE]
        close.restype = wintypes.BOOL

        class HandleInfo(ctypes.Structure):
            _fields_ = [("attributes", wintypes.DWORD), ("created", wintypes.FILETIME),
                        ("accessed", wintypes.FILETIME), ("written", wintypes.FILETIME),
                        ("volume", wintypes.DWORD), ("size_high", wintypes.DWORD),
                        ("size_low", wintypes.DWORD), ("links", wintypes.DWORD),
                        ("index_high", wintypes.DWORD), ("index_low", wintypes.DWORD)]

        getinfo = kernel.GetFileInformationByHandle
        getinfo.argtypes = [wintypes.HANDLE, ctypes.POINTER(HandleInfo)]
        getinfo.restype = wintypes.BOOL
        invalid = ctypes.c_void_p(-1).value
        try:
            for component in (*reversed(path.parents), path):
                leaf = component == path
                handle = create(str(component), 0x80000000 if leaf else 0x80,
                                1 if leaf else 3, None, 3, 0x02200000, None)
                if handle == invalid:
                    raise InventoryError("GUARDED_OPEN_FAILED")
                handles.append(handle)
                info = HandleInfo()
                if not getinfo(handle, ctypes.byref(info)):
                    raise InventoryError("GUARDED_OPEN_FAILED")
                if info.attributes & 0x400:
                    raise InventoryError("SYMLINK_OR_REPARSE_POINT")
                if bool(info.attributes & 0x10) == leaf:
                    raise InventoryError("NOT_REGULAR_FILE" if leaf else "NON_DIRECTORY_ANCESTOR")
            fd = msvcrt.open_osfhandle(handles[-1], os.O_RDONLY | os.O_BINARY)
            handles.pop()  # file object now owns this handle
            file = os.fdopen(fd, "rb")
            if not stat.S_ISREG(os.fstat(file.fileno()).st_mode):
                raise InventoryError("NOT_REGULAR_FILE")
            yield file
        finally:
            if file is not None:
                file.close()
            for handle in reversed(handles):
                close(handle)
    else:
        if not hasattr(os, "O_NOFOLLOW") or os.open not in os.supports_dir_fd:
            raise InventoryError("SAFE_OPEN_UNAVAILABLE")
        try:
            handles.append(os.open(path.anchor, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW))
            for part in path.parts[1:-1]:
                handles.append(os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=handles[-1]))
            fd = os.open(path.name, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK, dir_fd=handles[-1])
            file = os.fdopen(fd, "rb")
            if not stat.S_ISREG(os.fstat(file.fileno()).st_mode):
                raise InventoryError("NOT_REGULAR_FILE")
            yield file
        finally:
            if file is not None:
                file.close()
            for fd in reversed(handles):
                os.close(fd)


def _hash_file(path: Path, identity: dict, budget: ByteBudget) -> str:
    with _open_regular(path) as file:
        before = _stamp(os.fstat(file.fileno()))
        if before != identity:
            raise InventoryError("CHANGED_AFTER_PLAN")
        remaining = before["size"]
        digest = hashlib.sha256()
        while remaining:
            block = budget.read(file, min(CHUNK, remaining))
            if not block:
                raise InventoryError("MUTATED_DURING_READ")
            digest.update(block)
            remaining -= len(block)
        if budget.read(file, 1) or _stamp(os.fstat(file.fileno())) != before:
            raise InventoryError("MUTATED_DURING_READ")
        if _stamp(_metadata(path)) != before:
            raise InventoryError("PATH_IDENTITY_CHANGED")
        return digest.hexdigest()


def _independence(source_root, copy_root, source, copy) -> str:
    if source["device"] == copy["device"] and source["inode"] == copy["inode"]:
        return "SAME_FILE_OR_HARDLINK"
    if source_root["failure_domain"] == copy_root["failure_domain"]:
        return "SHARED_DECLARED_FAILURE_DOMAIN"
    if source["device"] == copy["device"]:
        return "SHARED_FILESYSTEM"
    # The operator declaration is still necessary: separate partitions alone
    # do not prove separate disks, hosts, credentials or disaster domains.
    return "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN"


def verify(manifest: dict, *, byte_budget: int | None, confirm_plan: str,
           environ: Mapping[str, str] | None = None) -> dict:
    """Fresh full hashes, bounded IO; stat identity is only a mutation guard."""
    inventory = plan(manifest, byte_budget=byte_budget, environ=environ)
    if inventory["status"] != "READY" or confirm_plan != inventory["plan_sha256"]:
        return {"schema": "vkm-unique-recovery-verification/1", "tool": TOOL, "status": "BLOCKED",
                "reason": inventory["blocker"] or "PLAN_CHANGED_OR_UNCONFIRMED", "bytes_read": 0,
                "current_plan_sha256": inventory["plan_sha256"]}
    roots, _ = _resolve(manifest, os.environ if environ is None else environ)
    definitions = {r["root_id"]: r for r in manifest["roots"]}
    items = {i["logical_id"]: i for i in manifest["items"]}
    budget, rows = ByteBudget(byte_budget), []
    # Retain identities and full hashes for a second pass. Stat is never used as
    # a shortcut for content equality, including the end-of-verification guard.
    observations = []
    for item_plan in inventory["items"]:
        item = items[item_plan["logical_id"]]
        row = {"logical_id": item["logical_id"], "declared_classification": item["classification"],
               "source_status": item_plan["source"]["status"], "backup_status": "NOT_VERIFIED",
               "recovery_classification": "REPRODUCIBLE" if item["classification"] == "REPRODUCIBLE" else "UNBACKED_UNIQUE",
               "copies": [], "reproduction_status": "DECLARED_NOT_DRILLED" if item["classification"] == "REPRODUCIBLE" else "NOT_APPLICABLE"}
        rows.append(row)
        if item["mutable"]:
            row["source_status"] = "MUTABLE_REQUIRES_QUIESCENT_SNAPSHOT"
            continue
        source = item_plan["source"]
        if source["status"] != "REGULAR":
            continue
        source_path = roots[item["source"]["root_id"]] / item["source"]["path"]
        try:
            sha = _hash_file(source_path, source["identity"], budget)
            row["source_sha256"] = sha
            row["source_status"] = "HASH_VERIFIED" if item.get("expected_sha256", sha) == sha else "EXPECTED_HASH_MISMATCH"
            observations.append((source_path, source["identity"], row, sha))
        except (OSError, InventoryError) as exc:
            row["source_status"] = _failure(exc)
            continue
        if row["source_status"] != "HASH_VERIFIED":
            continue
        row["source_identity_scope"] = "PINNED_EXPECTED_SHA256" if "expected_sha256" in item else "CURRENT_BYTES_ONLY"
        for index, (ref, copy) in enumerate(zip(item["copies"], item_plan["copies"])):
            proof = {"copy_index": index, "root_id": ref["root_id"], "status": copy["status"]}
            row["copies"].append(proof)
            if copy["status"] != "REGULAR":
                continue
            independence = _independence(definitions[item["source"]["root_id"]], definitions[ref["root_id"]],
                                         source["identity"], copy["identity"])
            proof["independence"] = independence
            path = roots[ref["root_id"]] / ref["path"]
            try:
                copy_sha = _hash_file(path, copy["identity"], budget)
                proof["sha256"] = copy_sha
                proof["byte_equality"] = copy_sha == sha and copy["size_bytes"] == source["size_bytes"]
                proof["status"] = ("VERIFIED_INDEPENDENT_COPY" if independence == "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN"
                                   else "EQUAL_COPY_NOT_INDEPENDENT") if proof["byte_equality"] else "HASH_MISMATCH"
                observations.append((path, copy["identity"], row, copy_sha))
            except (OSError, InventoryError) as exc:
                proof["status"] = _failure(exc)
    for path, identity, row, expected_sha in observations:
        try:
            if _hash_file(path, identity, budget) != expected_sha:
                raise InventoryError("MUTATED_DURING_VERIFICATION")
        except (OSError, InventoryError):
            row["source_status"] = "MUTATED_DURING_VERIFICATION"
            for copy in row["copies"]:
                if copy["status"] == "VERIFIED_INDEPENDENT_COPY":
                    copy["status"] = "INVALIDATED_BY_MUTATION"
    for row in rows:
        if row["source_status"] == "HASH_VERIFIED" and any(p["status"] == "VERIFIED_INDEPENDENT_COPY" for p in row["copies"]):
            row["backup_status"] = "VERIFIED_INDEPENDENT_COPY"
            row["recovery_classification"] = row["declared_classification"]
    failed = any(r["source_status"] != "HASH_VERIFIED" or r["recovery_classification"] == "UNBACKED_UNIQUE" for r in rows)
    return {"schema": "vkm-unique-recovery-verification/1", "tool": TOOL,
            "status": "FAIL" if failed else "PASS_WITH_REPRODUCTION_NOT_RUN" if any(r["declared_classification"] == "REPRODUCIBLE" for r in rows) else "PASS",
            "manifest_sha256": inventory["manifest_sha256"], "plan_sha256": confirm_plan,
            "byte_budget": byte_budget, "bytes_read": budget.used, "full_hash_passes": 2,
            "physical_failure_domains": "OPERATOR_ATTESTATION_REQUIRED",
            "restore_status": "NOT_RUN", "counts": {"items": len(rows),
                "unbacked_unique": sum(r["recovery_classification"] == "UNBACKED_UNIQUE" for r in rows),
                "source_unverified": sum(r["source_status"] != "HASH_VERIFIED" for r in rows),
                "verified_independent_copies": sum(r["backup_status"] == "VERIFIED_INDEPENDENT_COPY" for r in rows),
                "reproduction_not_drilled": sum(r["reproduction_status"] == "DECLARED_NOT_DRILLED" for r in rows)},
            "items": rows}


DRILL_PAYLOAD = b"VKM SYNTHETIC RECOVERY FIXTURE / no real originals\n" + bytes(range(256)) * 4
DRILL_BUDGET = 6 * (len(DRILL_PAYLOAD) + 1)


def _write_new(path: Path, data: bytes):
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as file:
        file.write(data)
        file.flush()
        os.fsync(file.fileno())


def _copy_synthetic(source: Path, target: Path, budget: ByteBudget):
    identity = _stamp(_metadata(source))
    with _open_regular(source) as file:
        if _stamp(os.fstat(file.fileno())) != identity:
            raise InventoryError("SYNTHETIC_INPUT_CHANGED")
        # This function is private to the fixed small drill, never exposed as a
        # real restore API. Whole payload equality prevents arbitrary input use.
        payload = budget.read(file, len(DRILL_PAYLOAD))
        if budget.read(file, 1) or payload != DRILL_PAYLOAD or _stamp(os.fstat(file.fileno())) != identity:
            raise InventoryError("NOT_THE_SYNTHETIC_FIXTURE")
    _write_new(target, payload)


def synthetic_drill(sandbox: Path, *, byte_budget: int | None) -> dict:
    """A fixed generated fixture only; does not accept original/copy locators."""
    if type(byte_budget) is not int or byte_budget < DRILL_BUDGET:
        return {"schema": "vkm-unique-recovery-drill/1", "status": "BLOCKED", "reason": "BYTE_BUDGET_REQUIRED_OR_INSUFFICIENT", "bytes_read": 0}
    sandbox, temporary = _absolute(sandbox), _absolute(tempfile.gettempdir())
    temp_info = temporary.lstat()
    if _indirect(temp_info) or not stat.S_ISDIR(temp_info.st_mode):
        raise InventoryError("UNSAFE_SYSTEM_TEMP")
    inside_temp = False
    for parent in (*reversed(sandbox.parent.parents), sandbox.parent):
        info = parent.lstat()
        if _indirect(info) or not stat.S_ISDIR(info.st_mode):
            raise InventoryError("UNSAFE_SANDBOX_PARENT")
        # File identity also handles Windows 8.3 aliases without resolving a
        # junction or silently walking a symbolic link.
        inside_temp |= os.path.samestat(info, temp_info)
    if not inside_temp:
        raise InventoryError("NEW_SYSTEM_TEMP_CHILD_REQUIRED")
    # No exist_ok, overwrite, deletion, cleanup, or user-selectable source path.
    sandbox.mkdir(mode=0o700)
    budget = ByteBudget(byte_budget)
    source, copy, restored = (sandbox / name for name in ("synthetic-original.bin", "synthetic-copy.bin", "synthetic-restored.bin"))
    _write_new(source, DRILL_PAYLOAD)
    source_identity = _stamp(_metadata(source))
    before = _hash_file(source, source_identity, budget)
    _copy_synthetic(source, copy, budget)
    _copy_synthetic(copy, restored, budget)
    copy_sha = _hash_file(copy, _stamp(_metadata(copy)), budget)
    restored_sha = _hash_file(restored, _stamp(_metadata(restored)), budget)
    after = _hash_file(source, source_identity, budget)
    if len({before, copy_sha, restored_sha, after}) != 1:
        raise InventoryError("SYNTHETIC_RESTORE_MISMATCH")
    result = {"schema": "vkm-unique-recovery-drill/1", "tool": TOOL, "status": "PASS",
              "scope": "GENERATED_SYNTHETIC_BYTES_ONLY", "original_unchanged": True,
              "original_sha256": before, "copy_sha256": copy_sha, "restored_sha256": restored_sha,
              "bytes_per_file": len(DRILL_PAYLOAD), "byte_budget": byte_budget, "bytes_read": budget.used,
              "independent_backup": "NOT_RUN", "real_restore": "NOT_RUN", "power_loss_durability": "NOT_RUN"}
    _write_new(sandbox / "receipt.json", _bytes(result) + b"\n")
    return result


def _load_manifest(path: Path) -> dict:
    info = _metadata(path)
    if info.st_size > MAX_MANIFEST_BYTES:
        raise InventoryError("MANIFEST_LIMIT")
    with _open_regular(path) as file:
        data = file.read(MAX_MANIFEST_BYTES + 1)
    if len(data) > MAX_MANIFEST_BYTES:
        raise InventoryError("MANIFEST_LIMIT")

    def unique_fields(pairs):
        value = {}
        for key, field in pairs:
            if key in value:
                raise InventoryError("DUPLICATE_JSON_FIELD")
            value[key] = field
        return value

    try:
        return validate_manifest(json.loads(data, object_pairs_hook=unique_fields))
    except (ValueError, TypeError, KeyError, RecursionError):
        raise InventoryError("INVALID_MANIFEST") from None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("plan", "verify"):
        part = sub.add_parser(command)
        part.add_argument("--manifest", type=Path, required=True)
        part.add_argument("--byte-budget", type=int)
        if command == "verify":
            part.add_argument("--confirm-plan", required=True)
    part = sub.add_parser("synthetic-drill")
    part.add_argument("--sandbox", type=Path, required=True)
    part.add_argument("--byte-budget", type=int)
    args = parser.parse_args(argv)
    try:
        if args.command == "synthetic-drill":
            result = synthetic_drill(args.sandbox, byte_budget=args.byte_budget)
        else:
            manifest = _load_manifest(args.manifest)
            result = plan(manifest, byte_budget=args.byte_budget) if args.command == "plan" else verify(
                manifest, byte_budget=args.byte_budget, confirm_plan=args.confirm_plan)
        print(json.dumps(result, sort_keys=True, ensure_ascii=True))
        return 0 if result["status"] in {"READY", "PASS", "PASS_WITH_REPRODUCTION_NOT_RUN"} else 1
    except (OSError, ValueError, TypeError, KeyError, RecursionError) as exc:
        print(json.dumps({"status": "BLOCKED", "reason": _failure(exc) if isinstance(exc, (OSError, InventoryError)) else "INVALID_MANIFEST"}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
