"""Explicit recovery capture uses generated bytes; never touches actual backups."""
from __future__ import annotations

from contextlib import contextmanager
from collections import Counter
from copy import deepcopy
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import sys

import pytest

SPEC = importlib.util.spec_from_file_location("vkm_frozen_inventory_test", Path(__file__).resolve().parents[2] / "infra/recovery/frozen_inventory.py")
F = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = F
SPEC.loader.exec_module(F)


@pytest.fixture
def inputs(tmp_path):
    source = tmp_path / "source"
    source.mkdir()
    (source / "a.bin").write_bytes(b"ABCD")
    (source / "b.bin").write_bytes(b"012345")
    manifest = {"schema": F.R.SCHEMA, "roots": [
        {"root_id": "original", "location_env": "FROZEN_TEST_SOURCE", "failure_domain": "test-one", "role": "ORIGINAL"}],
        "items": [{"logical_id": name, "classification": "CANONICAL", "source": {"root_id": "original", "path": name + ".bin"},
                   "mutable": False, "copies": []} for name in ("a", "b")]}
    return manifest, {"FROZEN_TEST_SOURCE": str(source)}, source


def pin(inputs, budget=1000):
    manifest, env, _ = inputs
    return F.PinnedFileSet(manifest, byte_budget=budget, max_seconds=30, environ=env)


def test_capture_preserves_explicit_denominator_and_originals(inputs):
    _, _, source = inputs
    before = {p.name: p.read_bytes() for p in source.iterdir()}
    with pin(inputs) as captured:
        assert captured.capture["status"] == "EXPLICIT_BYTES_PINNED"
        assert captured.capture["file_count"] == 2
        assert captured.capture["total_bytes"] == 10
        assert captured.capture["bytes_read"] == 20
        assert captured.capture["backup"] == captured.capture["restore"] == "NOT_RUN"
        assert captured.capture["semantic_uniqueness"] == "UNKNOWN"
        assert "NOT_ATOMIC_FILESYSTEM_SNAPSHOT" in captured.capture["snapshot_scope"]
        assert captured.capture["existing_mmap_writer_exclusion"] == "NOT_PROVEN"
        assert str(source) not in json.dumps(captured.capture)
        (source / "new.bin").write_bytes(b"not part of the declared set")
        assert captured.read_pinned("a") == b"ABCD"
        assert captured.recheck()["status"] == "SOURCE_BYTES_AND_IDENTITIES_UNCHANGED"
        assert captured.capture["file_count"] == 2
    assert {name: (source / name).read_bytes() for name in before} == before
    with pytest.raises(F.R.InventoryError, match="PINNED_HANDLE_UNAVAILABLE"):
        captured.read_pinned("a")


def test_all_handles_open_before_first_content_read(inputs, monkeypatch):
    active = Counter()
    original = F.R._open_regular

    @contextmanager
    def tracked(path):
        with original(path) as file:
            if path.name.endswith(".bin"):
                active[path.name] += 1
            try:
                yield file
            finally:
                active[path.name] -= 1
                if not active[path.name]:
                    del active[path.name]

    original_pass = F.PinnedFileSet._hash_pass

    def checked_pass(self):
        assert set(active) == {"a.bin", "b.bin"}
        return original_pass(self)

    monkeypatch.setattr(F.R, "_open_regular", tracked)
    monkeypatch.setattr(F.PinnedFileSet, "_hash_pass", checked_pass)
    with pin(inputs) as captured:
        assert captured.capture["file_count"] == 2
    assert not active


@pytest.mark.parametrize("mutation", ["missing", "mutable", "expected_hash", "copies", "budget"])
def test_incomplete_or_unsupported_capture_is_blocked(inputs, mutation):
    manifest, _, source = inputs
    budget = 1000
    if mutation == "missing":
        (source / "b.bin").unlink()
    elif mutation == "mutable":
        manifest["items"][0]["mutable"] = True
    elif mutation == "expected_hash":
        manifest["items"][0]["expected_sha256"] = "0" * 64
    elif mutation == "copies":
        manifest["roots"].append({"root_id": "copy", "location_env": "FROZEN_TEST_COPY", "failure_domain": "test-two", "role": "COPY"})
        manifest["items"][0]["copies"] = [{"root_id": "copy", "path": "a.bin"}]
    else:
        budget = 19
    with pytest.raises(F.R.InventoryError):
        with pin(inputs, budget=budget):
            pytest.fail("incomplete capture accepted")
    # No retained lock after failure.
    (source / "a.bin").write_bytes(b"still writable")


def test_content_equality_is_checked_after_copy_even_if_stat_is_uninformative(inputs, monkeypatch):
    if os.name == "nt":
        with pin(inputs) as captured:
            with pytest.raises(PermissionError):
                (inputs[2] / "a.bin").write_bytes(b"WXYZ")
            assert captured.recheck()["status"] == "SOURCE_BYTES_AND_IDENTITIES_UNCHANGED"
        return
    with pin(inputs) as captured:
        original_stamp = captured._handles["a"][2]
        original_native = captured._handles["a"][3]
        (inputs[2] / "a.bin").write_bytes(b"WXYZ")
        real_stamp = F.R._stamp
        real_change = F._change_stamp
        monkeypatch.setattr(F.R, "_stamp", lambda s: original_stamp if s.st_ino == original_stamp["inode"] else real_stamp(s))
        monkeypatch.setattr(F, "_change_stamp", lambda f: original_native if os.fstat(f.fileno()).st_ino == original_stamp["inode"] else real_change(f))
        with pytest.raises(F.R.InventoryError, match="PINNED_SOURCE_CHANGED"):
            captured.recheck()


def test_under_budget_cannot_deliver_copy_bytes(inputs):
    with pin(inputs, budget=24) as captured:
        assert captured.read_pinned("a") == b"ABCD"
        with pytest.raises(F.R.InventoryError, match="BYTE_BUDGET_EXCEEDED"):
            captured.read_pinned("b")


def test_time_and_handle_limits_are_explicit(inputs):
    manifest, env, _ = inputs
    for value in (None, True, 0, 301):
        with pytest.raises(F.R.InventoryError, match="TIME_BUDGET_REQUIRED"):
            F.PinnedFileSet(manifest, byte_budget=1000, max_seconds=value, environ=env)
    wide = deepcopy(manifest)
    wide["items"] = [{**wide["items"][0], "logical_id": f"x{i}", "source": {"root_id": "original", "path": f"x{i}.bin"}} for i in range(65)]
    with pytest.raises(F.R.InventoryError, match="OPEN_HANDLE_LIMIT"):
        F.PinnedFileSet(wide, byte_budget=1000, max_seconds=30, environ=env)


def test_successful_receipt_has_exact_source_byte_hash(inputs):
    with pin(inputs) as captured:
        a = next(i for i in captured.capture["files"] if i["logical_id"] == "a")
        assert a["sha256"] == hashlib.sha256(b"ABCD").hexdigest()
        expected = "WINDOWS_HANDLE_WRITE_DELETE_DENIED" if os.name == "nt" else "NOT_PROVEN_POSIX"
        assert captured.capture["write_exclusion"] == expected


def test_mutable_source_requires_explicit_windows_guard_and_remains_declared_mutable(inputs):
    manifest, env, source = inputs
    manifest["items"][0]["mutable"] = True
    if os.name != "nt":
        with pytest.raises(F.R.InventoryError, match="MUTABLE_WRITE_EXCLUSION_UNAVAILABLE"):
            F.PinnedFileSet(manifest, byte_budget=1000, max_seconds=30, environ=env,
                            mutable_policy="GUARDED_WINDOWS_BYTES_ONLY")
        return
    with pytest.raises(F.R.InventoryError, match="BYTE_BUDGET_EXCEEDED"):
        with F.PinnedFileSet(manifest, byte_budget=19, max_seconds=30, environ=env,
                             mutable_policy="GUARDED_WINDOWS_BYTES_ONLY"):
            pytest.fail("mutable full reads not reserved before capture")
    with F.PinnedFileSet(manifest, byte_budget=1000, max_seconds=30, environ=env,
                         mutable_policy="GUARDED_WINDOWS_BYTES_ONLY") as captured:
        assert captured.capture["mutable_sources"] == ["a"]
        assert manifest["items"][0]["mutable"] is True
        assert captured.capture["mutable_policy"] == "GUARDED_WINDOWS_BYTES_ONLY"
        with pytest.raises(PermissionError):
            (source / "a.bin").write_bytes(b"change")
        assert captured.recheck()["status"] == "SOURCE_BYTES_AND_IDENTITIES_UNCHANGED"
