"""Recovery evidence uses generated bytes only; no actual corpus or backup reads."""
from __future__ import annotations

from copy import deepcopy
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import sys

import pytest


SCRIPT = Path(__file__).resolve().parents[2] / "infra/recovery/unique_inventory.py"
SPEC = importlib.util.spec_from_file_location("vkm_unique_inventory_test", SCRIPT)
R = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = R
SPEC.loader.exec_module(R)


@pytest.fixture
def inventory(tmp_path):
    source, backup = tmp_path / "private-source", tmp_path / "private-copy"
    source.mkdir()
    backup.mkdir()
    (source / "artifact.bin").write_bytes(b"ABCD")
    (backup / "artifact.bin").write_bytes(b"ABCD")
    manifest = {"schema": R.SCHEMA, "roots": [
        {"root_id": "original", "location_env": "INVENTORY_SOURCE", "failure_domain": "host-one", "role": "ORIGINAL"},
        {"root_id": "backup", "location_env": "INVENTORY_COPY", "failure_domain": "host-two", "role": "COPY"}],
        "items": [{"logical_id": "unique-artifact", "classification": "CANONICAL",
                   "source": {"root_id": "original", "path": "artifact.bin"}, "mutable": False,
                   "copies": [{"root_id": "backup", "path": "artifact.bin"}]}]}
    env = {"INVENTORY_SOURCE": str(source), "INVENTORY_COPY": str(backup)}
    return manifest, env, source, backup


def run_verify(manifest, env, budget=100):
    plan = R.plan(manifest, byte_budget=budget, environ=env)
    return R.verify(manifest, byte_budget=budget, environ=env, confirm_plan=plan["plan_sha256"])


def test_plan_is_metadata_only_and_budget_is_mandatory(inventory, monkeypatch):
    manifest, env, source, backup = inventory
    from contextlib import contextmanager
    real_open = R._open_regular

    @contextmanager
    def metadata_only(path):
        with real_open(path) as file:
            class MetadataHandle:
                def fileno(self):
                    return file.fileno()

                def read(self, *args):
                    pytest.fail("plan must not read file contents")
            yield MetadataHandle()

    monkeypatch.setattr(R, "_open_regular", metadata_only)
    before = sorted(p.relative_to(source.parent) for p in source.parent.rglob("*"))
    for budget, status in ((None, "BLOCKED"), (0, "BLOCKED"), (True, "BLOCKED"), (19, "BLOCKED"), (20, "READY")):
        result = R.plan(manifest, byte_budget=budget, environ=env)
        assert result["status"] == status and result["bytes_read"] == 0
        assert result["max_bytes_to_read"] == 20
        assert result["items"][0]["backup_status"] == "NOT_VERIFIED"
        assert result["items"][0]["recovery_classification"] == "UNBACKED_UNIQUE"
    assert sorted(p.relative_to(source.parent) for p in source.parent.rglob("*")) == before


def test_current_bytes_on_same_filesystem_are_not_an_independent_backup(inventory):
    manifest, env, source, backup = inventory
    result = run_verify(manifest, env)
    row = result["items"][0]
    assert result["status"] == "FAIL" and result["bytes_read"] == 16, result
    assert row["source_sha256"] == hashlib.sha256(b"ABCD").hexdigest()
    assert row["copies"][0]["byte_equality"] is True
    assert row["copies"][0]["independence"] == "SHARED_FILESYSTEM"
    assert row["recovery_classification"] == "UNBACKED_UNIQUE"


def test_independence_requires_both_distinct_filesystem_and_operator_domain():
    a, b = {"failure_domain": "a"}, {"failure_domain": "b"}
    assert R._independence(a, b, {"device": 1, "inode": 9}, {"device": 1, "inode": 9}) == "SAME_FILE_OR_HARDLINK"
    assert R._independence(a, a, {"device": 1, "inode": 9}, {"device": 2, "inode": 9}) == "SHARED_DECLARED_FAILURE_DOMAIN"
    assert R._independence(a, b, {"device": 1, "inode": 9}, {"device": 2, "inode": 9}) == "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN"


def test_simulated_remote_copy_requires_actual_full_byte_equality(inventory, monkeypatch):
    manifest, env, source, backup = inventory
    # Storage topology is simulated; byte reads and hashes are real. The native
    # same-filesystem test above prevents claiming real independent backup here.
    monkeypatch.setattr(R, "_independence", lambda *a: "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN")
    first = run_verify(manifest, env)
    assert first["status"] == "PASS"
    assert first["items"][0]["backup_status"] == "VERIFIED_INDEPENDENT_COPY"
    old = (backup / "artifact.bin").stat()
    (backup / "artifact.bin").write_bytes(b"AXCD")
    os.utime(backup / "artifact.bin", ns=(old.st_atime_ns, old.st_mtime_ns))
    second = run_verify(manifest, env)
    assert second["status"] == "FAIL"
    assert second["items"][0]["copies"][0]["status"] == "HASH_MISMATCH"
    assert second["items"][0]["recovery_classification"] == "UNBACKED_UNIQUE"


def test_changed_confirmed_plan_stops_before_content_read(inventory, monkeypatch):
    manifest, env, source, _ = inventory
    plan = R.plan(manifest, byte_budget=100, environ=env)
    (source / "artifact.bin").write_bytes(b"changed")
    monkeypatch.setattr(R, "_hash_file", lambda *args: pytest.fail("stale plan must not hash"))
    result = R.verify(manifest, byte_budget=100, environ=env, confirm_plan=plan["plan_sha256"])
    assert result["status"] == "BLOCKED" and result["bytes_read"] == 0
    assert result["reason"] == "PLAN_CHANGED_OR_UNCONFIRMED"


@pytest.mark.parametrize("state", ["missing", "mutable", "root-unavailable", "expected-hash-mismatch", "io-error"])
def test_unavailable_or_mutable_original_never_receives_backup_pass(inventory, monkeypatch, state):
    manifest, env, source, _ = inventory
    if state == "missing":
        (source / "artifact.bin").unlink()
    elif state == "mutable":
        manifest["items"][0]["mutable"] = True
    elif state == "root-unavailable":
        env.pop("INVENTORY_SOURCE")
    elif state == "expected-hash-mismatch":
        manifest["items"][0]["expected_sha256"] = "0" * 64
    else:
        def fail(*args):
            raise PermissionError("PRIVATE CONTENT must never be logged")
        monkeypatch.setattr(R, "_hash_file", fail)
    result = run_verify(manifest, env)
    assert result["status"] == "FAIL"
    assert result["items"][0]["recovery_classification"] == "UNBACKED_UNIQUE"
    assert result["items"][0]["backup_status"] == "NOT_VERIFIED"
    assert "PRIVATE CONTENT" not in json.dumps(result)


def test_mutation_after_hash_invalidates_previously_equal_copy(inventory, monkeypatch):
    manifest, env, source, backup = inventory
    original_hash = R._hash_file
    monkeypatch.setattr(R, "_independence", lambda *a: "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN")
    mutations = []

    def mutate_after_copy(path, *args):
        result = original_hash(path, *args)
        if path.parent == backup:
            (source / "artifact.bin").write_bytes(b"EVIL")
            mutations.append(True)
        return result

    monkeypatch.setattr(R, "_hash_file", mutate_after_copy)
    result = run_verify(manifest, env)
    assert mutations, "test must replace source bytes after the copy has been read"
    assert result["status"] == "FAIL"
    assert result["items"][0]["source_status"] == "MUTATED_DURING_VERIFICATION"
    assert result["items"][0]["copies"][0]["status"] == "INVALIDATED_BY_MUTATION"


def test_second_hash_pass_detects_mutation_when_metadata_clock_is_coarse(inventory, monkeypatch):
    manifest, env, source, backup = inventory
    real_stamp, real_hash = R._stamp, R._hash_file
    monkeypatch.setattr(R, "_stamp", lambda value: {**real_stamp(value), "ctime_ns": 0, "mtime_ns": 0})
    monkeypatch.setattr(R, "_independence", lambda *a: "DISTINCT_FILESYSTEM_AND_DECLARED_FAILURE_DOMAIN")

    def late_mutation(path, *args):
        result = real_hash(path, *args)
        if path.parent == backup:
            (source / "artifact.bin").write_bytes(b"EVIL")
        return result

    monkeypatch.setattr(R, "_hash_file", late_mutation)
    result = run_verify(manifest, env)
    assert result["full_hash_passes"] == 2 and result["bytes_read"] == 16
    assert result["status"] == "FAIL"
    assert result["items"][0]["source_status"] == "MUTATED_DURING_VERIFICATION"


def test_hardlink_is_not_backup(inventory):
    manifest, env, source, backup = inventory
    (backup / "artifact.bin").unlink()
    os.link(source / "artifact.bin", backup / "artifact.bin")
    result = run_verify(manifest, env)
    assert result["items"][0]["copies"][0]["independence"] == "SAME_FILE_OR_HARDLINK"
    assert result["status"] == "FAIL"


@pytest.mark.parametrize("path", ["../outside", "/absolute", "a/../outside", "a//b", "a/./b", "a\\b", "x:stream", "NUL", "com1.txt", "a.", "a ", "*.pdf"])
def test_unsafe_locators_rejected(inventory, path):
    manifest, *_ = inventory
    manifest["items"][0]["source"]["path"] = path
    with pytest.raises(R.InventoryError):
        R.validate_manifest(manifest)


def test_duplicate_ids_and_user_supplied_unbacked_class_are_rejected(inventory):
    manifest, *_ = inventory
    duplicate = deepcopy(manifest["items"][0])
    duplicate["logical_id"] = duplicate["logical_id"].upper()
    manifest["items"].append(duplicate)
    with pytest.raises(R.InventoryError, match="DUPLICATE_LOGICAL_ID"):
        R.validate_manifest(manifest)
    manifest["items"].pop()
    manifest["items"][0]["classification"] = "UNBACKED_UNIQUE"
    with pytest.raises(R.InventoryError, match="INVALID_CLASSIFICATION"):
        R.validate_manifest(manifest)


def test_reproducibility_is_explicit_and_never_claims_a_drill(inventory):
    manifest, env, *_ = inventory
    item = manifest["items"][0]
    item["classification"] = "REPRODUCIBLE"
    with pytest.raises(R.InventoryError):
        R.validate_manifest(manifest)
    item["reproduction"] = {"recipe_sha256": "1" * 64, "input_ids": []}
    result = run_verify(manifest, env)
    assert result["status"] == "PASS_WITH_REPRODUCTION_NOT_RUN"
    assert result["items"][0]["reproduction_status"] == "DECLARED_NOT_DRILLED"
    assert result["items"][0]["backup_status"] == "NOT_VERIFIED"
    item["reproduction"]["input_ids"] = [item["logical_id"]]
    with pytest.raises(R.InventoryError, match="REPRODUCTION_CYCLE"):
        R.validate_manifest(manifest)


def test_reparse_point_metadata_blocks_without_traversal(inventory, monkeypatch):
    manifest, env, source, _ = inventory
    real_lstat = Path.lstat

    def fake(path, *args, **kwargs):
        info = real_lstat(path, *args, **kwargs)
        if path == source:
            from types import SimpleNamespace
            return SimpleNamespace(st_mode=info.st_mode, st_file_attributes=0x400)
        return info

    monkeypatch.setattr(Path, "lstat", fake)
    result = R.plan(manifest, byte_budget=100, environ=env)
    assert result["items"][0]["source"]["status"] == "SYMLINK_OR_REPARSE_POINT"
    assert result["bytes_read"] == 0


def test_symlink_ancestor_is_never_followed(inventory):
    manifest, env, source, _ = inventory
    indirect = source.parent / "indirect"
    if os.name == "nt":
        # Directory junctions do not need Developer Mode's symlink privilege.
        import subprocess
        made = subprocess.run(["cmd", "/d", "/c", "mklink", "/J", str(indirect), str(source)],
                              capture_output=True)
        assert made.returncode == 0, "synthetic junction fixture unavailable"
    else:
        indirect.symlink_to(source, target_is_directory=True)
    env["INVENTORY_SOURCE"] = str(indirect)
    result = run_verify(manifest, env)
    assert result["items"][0]["source_status"] == "SYMLINK_OR_REPARSE_POINT"
    with pytest.raises((R.InventoryError, OSError)):
        with R._open_regular(indirect / "artifact.bin"):
            pytest.fail("must not follow indirect ancestor")


def test_receipt_contains_no_private_locators_or_contents(inventory):
    manifest, env, source, backup = inventory
    result = json.dumps(run_verify(manifest, env))
    assert "artifact.bin" not in result and str(source) not in result and str(backup) not in result
    assert "ABCD" not in result and "INVENTORY_SOURCE" not in result


def test_budget_stop_is_enforced_on_actual_reader():
    import io
    budget = R.ByteBudget(3)
    assert budget.read(io.BytesIO(b"abc"), 3) == b"abc"
    with pytest.raises(R.InventoryError, match="BYTE_BUDGET_EXCEEDED"):
        budget.read(io.BytesIO(b"x"), 1)
    assert budget.used == 3


def test_synthetic_drill_restores_bytes_and_preserves_original():
    # The qualification runner may keep pytest's basetemp on a persistent disk.
    # The restore command intentionally accepts only the actual system temp tree.
    with R.tempfile.TemporaryDirectory(prefix="vkm-unique-drill-test-") as parent:
        sandbox = Path(parent) / "drill"
        result = R.synthetic_drill(sandbox, byte_budget=R.DRILL_BUDGET)
        assert result["status"] == "PASS" and result["original_unchanged"] is True
        assert result["real_restore"] == result["independent_backup"] == "NOT_RUN"
        assert result["bytes_read"] <= R.DRILL_BUDGET
        files = [sandbox / name for name in ("synthetic-original.bin", "synthetic-copy.bin", "synthetic-restored.bin")]
        assert all(path.read_bytes() == R.DRILL_PAYLOAD for path in files)
        assert result["restored_sha256"] == hashlib.sha256(R.DRILL_PAYLOAD).hexdigest()
        assert json.loads((sandbox / "receipt.json").read_bytes()) == result
        with pytest.raises(FileExistsError):
            R.synthetic_drill(sandbox, byte_budget=R.DRILL_BUDGET)
        assert files[0].read_bytes() == R.DRILL_PAYLOAD


def test_drill_without_budget_and_outside_temp_do_not_write(tmp_path):
    target = tmp_path / "not-created"
    assert R.synthetic_drill(target, byte_budget=None)["status"] == "BLOCKED"
    assert not target.exists()
    outside = Path(R.tempfile.gettempdir()).anchor
    with pytest.raises(R.InventoryError, match="NEW_SYSTEM_TEMP_CHILD_REQUIRED"):
        R.synthetic_drill(Path(outside), byte_budget=R.DRILL_BUDGET)


def test_cli_invalid_manifest_does_not_echo_contents(tmp_path, capsys):
    file = tmp_path / "manifest.json"
    file.write_text('{"secret": "NEVER_PRINT_THIS"}', encoding="utf-8")
    assert R.main(["plan", "--manifest", str(file)]) == 1
    output = capsys.readouterr().out
    assert "NEVER_PRINT_THIS" not in output and str(file) not in output
    assert json.loads(output)["status"] == "BLOCKED"


def test_cli_plan_verify_and_duplicate_json(inventory, tmp_path, monkeypatch, capsys):
    manifest, env, *_ = inventory
    for key, value in env.items():
        monkeypatch.setenv(key, value)
    path = tmp_path / "operator-manifest.json"
    path.write_text(json.dumps(manifest), encoding="utf-8")
    assert R.main(["plan", "--manifest", str(path), "--byte-budget", "100"]) == 0
    planned = json.loads(capsys.readouterr().out)
    assert planned["status"] == "READY" and planned["bytes_read"] == 0
    assert R.main(["verify", "--manifest", str(path), "--byte-budget", "100", "--confirm-plan", planned["plan_sha256"]]) == 1
    receipt = json.loads(capsys.readouterr().out)
    assert receipt["counts"]["unbacked_unique"] == 1 and receipt["bytes_read"] == 16
    path.write_text('{"schema":"hidden","schema":"vkm-unique-inventory/1","roots":[],"items":[]}', encoding="utf-8")
    assert R.main(["plan", "--manifest", str(path)]) == 1
    assert json.loads(capsys.readouterr().out)["status"] == "BLOCKED"
